_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
ingress: false
labels: 'app: offsite-backups'
name: offsite-backups
namespace: offsite-backups
pvc: false
reloader: false
resources:
- configmaps.yaml
- cronjobs.yaml
- external-secrets.yaml
- rbac.yaml
service: false
serviceAccount: false
upstreamURL: ''
url: https://github.com/charlesthomas/homelab-offsite-backups
