_commit: v1.3.6
_src_path: ./homelab-template
additionalResources: ''
backups: false
helm: false
ingSecret: ''
ingress: false
labels: 'app: offsite-backups'
name: offsite-backups
namespace: offsite-backups
pvc: false
reloader: false
resources:
- configmaps.yaml
- cronjobs.yaml
- external-secrets.yaml
- rbac.yaml
service: false
serviceAccount: false
upstreamURL: ''
url: https://github.com/charlesthomas/homelab-offsite-backups
