---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: offsite-backups

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-offsite-backups
commonLabels:
  app: offsite-backups

resources:
- resources/configmaps.yaml
- resources/cronjobs.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: offsite-backups
      namespace: offsite-backups
      annotations:
        gethomepage.dev/href: https://offsite-backups.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: offsite-backups
        gethomepage.dev/name: offsite-backups
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
