---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: offsite-backups

commonLabels:
  app: offsite-backups

resources:
- configmaps.yaml
- cronjobs.yaml
- external-secrets.yaml
- namespaces.yaml
- rbac.yaml
