---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: offsite-backups

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-offsite-backups
commonLabels:
  app: offsite-backups

resources:
- resources/configmaps.yaml
- resources/cronjobs.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
