---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-script
  namespace: offsite-backups
data:
  sync.sh: |-
    mkdir /root/.ssh
    cp /ssh/* /root/.ssh
    chmod -R 600 /root/.ssh
    rsync --archive --compress --delete-after --no-owner --size-only --verbose /critical/ offsite-backups:/mnt/nas02/critical/
    rsync --archive --compress --delete-after --no-owner --size-only --verbose /media/ offsite-backups:/mnt/nas02/media/
    rsync --archive --compress --delete-after --no-owner --size-only --verbose /time-machine/ offsite-backups:/mnt/nas02/time-machine/
    rsync --archive --compress --delete-after --no-owner --size-only --verbose offsite-backups:/mnt/nas02/TMBackup/ /arborwood/
